import { Flame, Medal, Search, TrendingDown, TrendingUp } from "lucide-react";
import { AppShell } from "@/components/layout/app-shell";
import { Pill, Surface } from "@/components/ui/surface";
import { leaderboard } from "@/lib/data/content";

export default function LeaderboardPage() {
  return <AppShell title="Leaderboards" description="Human rankings stay separate from house-player exhibitions, so every competitive place means what it says.">
    <div className="flex flex-wrap gap-2">{["Rapid", "Blitz", "Bullet", "Classical", "Season 01", "Friends"].map((item, i) => <button key={item} className={`rounded-xl px-4 py-2 text-sm font-bold transition ${i === 0 ? "bg-[var(--accent)] text-[#031421]" : "border border-[var(--border)] bg-[var(--surface)] text-[var(--text-muted)] hover:text-[var(--text)]"}`}>{item}</button>)}</div>
    <div className="mt-6 grid gap-5 xl:grid-cols-[1fr_320px]">
      <Surface className="overflow-hidden"><div className="flex items-center justify-between border-b border-[var(--border)] p-5"><div><p className="font-bold">Global rapid</p><p className="mt-1 text-xs text-[var(--text-faint)]">Updated after each rated game</p></div><label className="flex items-center gap-2 rounded-xl bg-[var(--surface-soft)] px-3 py-2"><Search size={15} className="text-[var(--text-faint)]" /><input aria-label="Search players" placeholder="Find player" className="w-28 bg-transparent text-xs outline-none placeholder:text-[var(--text-faint)]" /></label></div><div>{leaderboard.map((player) => <div key={player.name} className="grid grid-cols-[42px_1fr_auto] items-center gap-3 border-b border-[var(--border)] px-5 py-4 last:border-0"><span className={`grid size-9 place-items-center rounded-xl text-sm font-black ${player.rank === 1 ? "bg-orange-400/15 text-orange-300" : "bg-[var(--surface-soft)] text-[var(--text-muted)]"}`}>{player.rank}</span><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-cyan-400/10 text-xl text-cyan-300">♞</span><div><p className="text-sm font-bold">{player.name} {"house" in player && player.house && <Pill className="ml-1 py-0 text-[9px]">House</Pill>}</p><p className="mt-1 text-[10px] text-[var(--text-faint)]">{player.country} · <Flame size={10} className="inline text-orange-300" /> {player.streak} streak</p></div></div><div className="text-right"><p className="text-lg font-black">{player.rating}</p><p className={`mt-1 flex items-center justify-end gap-1 text-[10px] font-bold ${player.trend >= 0 ? "text-emerald-400" : "text-red-400"}`}>{player.trend >= 0 ? <TrendingUp size={11} /> : <TrendingDown size={11} />}{player.trend > 0 ? "+" : ""}{player.trend}</p></div></div>)}</div></Surface>
      <div className="space-y-5"><Surface className="p-5"><div className="grid size-12 place-items-center rounded-2xl bg-violet-400/10 text-violet-300"><Medal size={23} /></div><p className="mt-5 text-sm font-bold">Your provisional place</p><p className="mt-2 text-3xl font-black">#1,842</p><p className="mt-1 text-xs text-[var(--text-muted)]">1,248 rapid · 7 games remain</p><div className="mt-5 h-2 overflow-hidden rounded-full bg-[var(--surface-raised)]"><div className="h-full w-[30%] rounded-full bg-violet-400" /></div></Surface><Surface className="p-5"><p className="text-sm font-bold">Season ends in</p><p className="mt-3 font-mono text-2xl font-black text-[var(--accent)]">19d 08h 42m</p><p className="mt-2 text-xs leading-5 text-[var(--text-muted)]">Finish 20 rated games to qualify for your seasonal placement badge.</p></Surface></div>
    </div>
  </AppShell>;
}
