"use client";

import { FormEvent, useMemo, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { AlertCircle, Bot, CalendarClock, CheckCircle2, Clock3, Eye, LoaderCircle, LockKeyhole, ShieldCheck, Trophy, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Pill, Surface } from "@/components/ui/surface";

type FormValues = { name: string; description: string; format: "arena" | "swiss" | "private"; visibility: "public" | "unlisted" | "private"; startsAt: string; baseMinutes: number; incrementSeconds: number; maxPlayers: number; rounds: number; durationMinutes: number; rated: boolean; allowHousePlayers: boolean; allowLateJoin: boolean };
const initial: FormValues = { name: "", description: "", format: "arena", visibility: "public", startsAt: "", baseMinutes: 10, incrementSeconds: 0, maxPlayers: 24, rounds: 5, durationMinutes: 90, rated: false, allowHousePlayers: true, allowLateJoin: true };
type Submission = { status: "idle" | "sending" | "error"; message?: string };

export function CreateTournamentForm() {
  const [values, setValues] = useState(initial);
  const [submission, setSubmission] = useState<Submission>({ status: "idle" });
  const requestKey = useRef(crypto.randomUUID());
  const router = useRouter();
  const update = <K extends keyof FormValues>(key: K, value: FormValues[K]) => setValues((current) => ({ ...current, [key]: value }));
  const timeLabel = `${values.baseMinutes}+${values.incrementSeconds}`;
  const startLabel = useMemo(() => values.startsAt ? new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(new Date(values.startsAt)) : "Choose a start time", [values.startsAt]);

  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setSubmission({ status: "sending" });
    try {
      const response = await fetch("/tournaments/create/submit", { method: "POST", headers: { "content-type": "application/json", "idempotency-key": requestKey.current }, body: JSON.stringify(values) });
      const payload = await response.json().catch(() => null) as { slug?: string; message?: string; error?: string } | null;
      if (!response.ok) throw new Error(payload?.message || payload?.error || "The tournament could not be created.");
      if (!payload?.slug) throw new Error("The tournament was created, but its page could not be opened.");
      router.push(`/tournaments/${payload.slug}`);
      router.refresh();
    } catch (error) { setSubmission({ status: "error", message: error instanceof Error ? error.message : "The tournament could not be created." }); }
  }

  return <form onSubmit={submit} className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_350px]">
    <div className="space-y-6"><Surface className="p-6"><SectionTitle n="1" title="Event identity" description="Give players enough context to decide whether the event fits." /><div className="mt-6 grid gap-5"><Field label="Tournament name" hint="3–120 characters"><input required minLength={3} maxLength={120} value={values.name} onChange={(e) => update("name", e.target.value)} placeholder="Friday Night Rapid" className={inputClass} /></Field><Field label="Description" hint="Optional · up to 1,200 characters"><textarea maxLength={1200} rows={4} value={values.description} onChange={(e) => update("description", e.target.value)} placeholder="Who is this event for, and how will it run?" className={`${inputClass} h-auto resize-y py-3`} /></Field><div className="grid gap-5 sm:grid-cols-2"><Field label="Format"><select value={values.format} onChange={(e) => update("format", e.target.value as FormValues["format"])} className={inputClass}><option value="arena">Arena</option><option value="swiss">Swiss</option><option value="private">Private event</option></select></Field><Field label="Visibility"><select value={values.visibility} onChange={(e) => update("visibility", e.target.value as FormValues["visibility"])} className={inputClass}><option value="public">Public listing</option><option value="unlisted">Link only</option><option value="private">Private</option></select></Field></div></div></Surface>
    <Surface className="p-6"><SectionTitle n="2" title="Schedule & chess" description="Times are shown in each player’s local timezone." /><div className="mt-6 grid gap-5 sm:grid-cols-2"><Field label="Start date and time"><input required type="datetime-local" value={values.startsAt} onChange={(e) => update("startsAt", e.target.value)} className={inputClass} /></Field><Field label="Maximum players"><input required type="number" min={2} max={512} value={values.maxPlayers} onChange={(e) => update("maxPlayers", Number(e.target.value))} className={inputClass} /></Field><Field label="Minutes per player"><input required type="number" min={1} max={1440} value={values.baseMinutes} onChange={(e) => update("baseMinutes", Number(e.target.value))} className={inputClass} /></Field><Field label="Increment in seconds"><input required type="number" min={0} max={600} value={values.incrementSeconds} onChange={(e) => update("incrementSeconds", Number(e.target.value))} className={inputClass} /></Field>{values.format === "arena" && <Field label="Arena duration in minutes"><input required type="number" min={20} max={480} value={values.durationMinutes} onChange={(e) => update("durationMinutes", Number(e.target.value))} className={inputClass} /></Field>}{values.format === "swiss" && <Field label="Rounds"><input required type="number" min={2} max={15} value={values.rounds} onChange={(e) => update("rounds", Number(e.target.value))} className={inputClass} /></Field>}</div></Surface>
    <Surface className="p-6"><SectionTitle n="3" title="Competition settings" description="These settings are recorded with the event and cannot be quietly changed after games begin." /><div className="mt-6 space-y-3"><Toggle icon={Trophy} title="Rated games" body="Apply the correct time-control rating after validated results." checked={values.rated} onChange={(checked) => update("rated", checked)} /><Toggle icon={Bot} title="Allow House Players" body="Clearly identified system opponents may fill configured open places." checked={values.allowHousePlayers} onChange={(checked) => update("allowHousePlayers", checked)} /><Toggle icon={CalendarClock} title="Allow late joining" body="Available for formats where late entry does not compromise pairing fairness." checked={values.allowLateJoin} onChange={(checked) => update("allowLateJoin", checked)} /></div></Surface></div>
    <aside className="space-y-5 xl:sticky xl:top-24 xl:self-start"><Surface className="overflow-hidden"><div className="h-1.5 bg-gradient-to-r from-cyan-400 via-violet-400 to-orange-400" /><div className="p-6"><div className="flex items-center justify-between"><Pill>{values.format === "swiss" ? `Swiss · ${values.rounds} rounds` : values.format === "arena" ? "Arena" : "Private event"}</Pill><span className="text-sm font-bold text-[var(--accent)]">{timeLabel}</span></div><h2 className="mt-5 text-2xl font-bold tracking-[-.04em]">{values.name.trim() || "Your tournament"}</h2><p className="mt-2 line-clamp-3 text-sm leading-6 text-[var(--text-muted)]">{values.description.trim() || "Add a short description so players know what makes this event worth joining."}</p><div className="mt-5 space-y-3"><PreviewFact icon={CalendarClock} label={startLabel} /><PreviewFact icon={Users} label={`Up to ${values.maxPlayers} players`} /><PreviewFact icon={values.visibility === "private" ? LockKeyhole : Eye} label={`${values.visibility.charAt(0).toUpperCase()}${values.visibility.slice(1)} visibility`} /></div><div className="mt-5 flex flex-wrap gap-2">{values.rated && <Pill>Rated</Pill>}{values.allowHousePlayers && <Pill><Bot size={12} />House pool</Pill>}{values.allowLateJoin && <Pill>Late join</Pill>}</div></div></Surface><Surface className="border-emerald-400/15 bg-emerald-400/[.05] p-5"><ShieldCheck size={20} className="text-emerald-300" /><h2 className="mt-4 font-bold">Organizer responsibility</h2><p className="mt-2 text-xs leading-5 text-[var(--text-muted)]">Publish accurate rules, moderate event chat, avoid changing competitive settings after entry, and disclose how House Players affect ratings or standings.</p></Surface>{submission.status === "error" && <div role="alert" className="flex gap-3 rounded-2xl border border-red-400/20 bg-red-400/10 p-4 text-sm text-red-200"><AlertCircle size={18} className="mt-0.5 shrink-0" /><span>{submission.message}</span></div>}<Button type="submit" size="lg" className="w-full" disabled={submission.status === "sending"}>{submission.status === "sending" ? <><LoaderCircle size={17} className="animate-spin" />Creating…</> : <><CheckCircle2 size={17} />Create tournament</>}</Button><p className="text-center text-[11px] leading-5 text-[var(--text-faint)]">A permanent account is required. Your event remains subject to capacity, moderation, and fair-play controls.</p></aside>
  </form>;
}

const inputClass = "mt-2 h-11 w-full rounded-xl border border-[var(--border-strong)] bg-[var(--surface-soft)] px-3 text-sm text-[var(--text)] outline-none transition focus:border-[var(--accent-muted)] focus:ring-2 focus:ring-[var(--accent-soft)]";
function Field({ label, hint, children }: { label: string; hint?: string; children: React.ReactNode }) { return <label className="text-sm font-bold">{label}{hint && <span className="ml-2 text-xs font-normal text-[var(--text-faint)]">{hint}</span>}{children}</label>; }
function SectionTitle({ n, title, description }: { n: string; title: string; description: string }) { return <div className="flex gap-3"><span className="grid size-8 shrink-0 place-items-center rounded-xl bg-[var(--accent-soft)] text-xs font-bold text-[var(--accent)]">{n}</span><div><h2 className="font-bold">{title}</h2><p className="mt-1 text-xs leading-5 text-[var(--text-muted)]">{description}</p></div></div>; }
function Toggle({ icon: Icon, title, body, checked, onChange }: { icon: typeof Trophy; title: string; body: string; checked: boolean; onChange: (checked: boolean) => void }) { return <label className="flex cursor-pointer items-start gap-4 rounded-2xl border border-[var(--border)] bg-[var(--surface-soft)] p-4"><Icon size={18} className="mt-0.5 shrink-0 text-[var(--accent)]" /><span className="min-w-0 flex-1"><span className="block text-sm font-bold">{title}</span><span className="mt-1 block text-xs leading-5 text-[var(--text-muted)]">{body}</span></span><input type="checkbox" className="toggle shrink-0" checked={checked} onChange={(e) => onChange(e.target.checked)} /></label>; }
function PreviewFact({ icon: Icon, label }: { icon: typeof Clock3; label: string }) { return <p className="flex items-center gap-2 text-xs text-[var(--text-muted)]"><Icon size={14} className="text-[var(--accent)]" />{label}</p>; }
