import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, CalendarDays, LockKeyhole, ShieldCheck, Sparkles, Users } from "lucide-react";
import { AppShell } from "@/components/layout/app-shell";
import { ButtonLink } from "@/components/ui/button";
import { Pill, Surface } from "@/components/ui/surface";
import { clubs } from "./data";

export const metadata: Metadata = { title: "Chess clubs", description: "Find welcoming chess clubs for endgames, blitz arenas, beginner study, and private events on Busted Minds Chess." };

export default function ClubsPage() { return <AppShell title="Clubs" description="Find a room with the right rhythm: study together, run private events, and keep useful games close." actions={<ButtonLink href="/auth?next=/clubs"><Users size={16} />Create a club</ButtonLink>}>
  <Surface className="relative overflow-hidden border-cyan-300/15 bg-[linear-gradient(135deg,rgba(25,198,237,.12),var(--surface)_56%)] p-6 sm:p-8"><div className="relative z-10 max-w-2xl"><Pill><Sparkles size={13} />Launch communities</Pill><h2 className="mt-4 text-3xl font-bold tracking-[-.04em]">Chess gets better when the room remembers you.</h2><p className="mt-3 text-sm leading-6 text-[var(--text-muted)]">Join open study rooms, request access to focused groups, or create a private home for friends. Permanent accounts are required for membership and club messages.</p><div className="mt-6 flex flex-wrap gap-3"><ButtonLink href="#discover">Explore clubs<ArrowRight size={16} /></ButtonLink><ButtonLink href="/guidelines" variant="secondary"><ShieldCheck size={16} />Club guidelines</ButtonLink></div></div><div aria-hidden className="absolute -right-6 -top-10 hidden text-[13rem] leading-none text-cyan-300/[.06] md:block">♚</div></Surface>
  <section id="discover" className="mt-8 scroll-mt-28"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="eyebrow">Discover</p><h2 className="mt-2 text-xl font-bold">Active launch clubs</h2></div><Pill><Users size={12} />{clubs.length} rooms to explore</Pill></div>
    <div className="mt-5 grid gap-5 lg:grid-cols-3">{clubs.map((club) => <Surface key={club.slug} className="group flex flex-col overflow-hidden"><div className="h-1.5" style={{ backgroundColor: club.color }} /><div className="flex flex-1 flex-col p-6"><div className="flex items-start justify-between gap-4"><span className="grid size-12 place-items-center rounded-2xl text-sm font-black" style={{ color: club.color, backgroundColor: `${club.color}18` }}>{club.initials}</span><Pill>{club.privacy === "Open" ? <Users size={12} /> : <LockKeyhole size={12} />}{club.privacy}</Pill></div><h3 className="mt-5 text-xl font-bold">{club.name}</h3><p className="mt-1 text-xs font-bold" style={{ color: club.color }}>{club.tagline}</p><p className="mt-3 flex-1 text-sm leading-6 text-[var(--text-muted)]">{club.description}</p><div className="mt-5 grid grid-cols-2 gap-2 text-xs"><div className="rounded-xl bg-[var(--surface-soft)] p-3"><p className="font-bold">{club.members} members</p><p className="mt-1 text-[var(--text-faint)]">{club.online} around now</p></div><div className="rounded-xl bg-[var(--surface-soft)] p-3"><p className="font-bold">{club.focus}</p><p className="mt-1 text-[var(--text-faint)]">Primary focus</p></div></div><Link href={`/clubs/${club.slug}`} className="mt-5 inline-flex items-center gap-1.5 text-sm font-bold text-[var(--accent)]">Visit club<ArrowRight size={15} className="transition group-hover:translate-x-1" /></Link></div></Surface>)}</div>
  </section>
  <div className="mt-8 grid gap-4 md:grid-cols-3"><Info icon={CalendarDays} title="Club events" body="Run private Arena or Swiss events with member-only standings and discussion." /><Info icon={ShieldCheck} title="Member controls" body="Owners can manage roles; every member can mute, block, and report." /><Info icon={LockKeyhole} title="Private by choice" body="Choose open membership, join requests, or an invite-only club for friends." /></div>
  </AppShell>; }

function Info({ icon: Icon, title, body }: { icon: typeof Users; title: string; body: string }) { return <div className="rounded-2xl border border-dashed border-[var(--border-strong)] p-5"><Icon size={18} className="text-[var(--accent)]" /><p className="mt-3 text-sm font-bold">{title}</p><p className="mt-2 text-xs leading-5 text-[var(--text-muted)]">{body}</p></div>; }
