import { ArrowRight, BookOpen, BrainCircuit, GraduationCap, Landmark, Play, Sparkles, Target } from "lucide-react";
import { AppShell } from "@/components/layout/app-shell";
import { ButtonLink } from "@/components/ui/button";
import { Pill, Surface } from "@/components/ui/surface";
import { learningTracks } from "@/lib/data/content";

export default function LearnPage() {
  return <AppShell title="Learn with a purpose." description="Short lessons, focused practice, and engine feedback connected to positions you actually play." actions={<ButtonLink href="/puzzles"><Target size={16} />Daily puzzle</ButtonLink>}>
    <Surface className="overflow-hidden p-7 sm:p-8"><div className="grid gap-8 md:grid-cols-[1fr_280px] md:items-center"><div><Pill className="text-violet-300"><Sparkles size={13} />Recommended next</Pill><h2 className="mt-4 text-3xl font-bold tracking-[-.04em]">The question to ask after every check</h2><p className="mt-3 max-w-xl text-sm leading-6 text-[var(--text-muted)]">A six-minute interactive lesson built from the one pattern that cost you time this week.</p><div className="mt-6 flex gap-3"><ButtonLink href="/learn/checks"><Play size={16} fill="currentColor" />Start lesson</ButtonLink><Pill>6 min</Pill><Pill>3 positions</Pill></div></div><div className="grid aspect-[4/3] place-items-center rounded-2xl bg-[radial-gradient(circle,rgba(167,139,250,.2),rgba(167,139,250,.04))] text-8xl text-violet-200">♛</div></div></Surface>
    <div className="mt-8 flex items-center justify-between"><h2 className="text-xl font-bold">Learning tracks</h2><ButtonLink href="/learn/library" variant="ghost" size="sm">Browse library<ArrowRight size={15} /></ButtonLink></div><div className="mt-4 grid gap-4 md:grid-cols-2">{learningTracks.map(({ title, lessons, progress, level, icon: Icon, color }) => <Surface key={title} className="p-5"><div className="flex items-start gap-4"><span className={`grid size-12 shrink-0 place-items-center rounded-2xl ${color === "orange" ? "bg-orange-400/10 text-orange-300" : color === "cyan" ? "bg-cyan-400/10 text-cyan-300" : color === "violet" ? "bg-violet-400/10 text-violet-300" : "bg-emerald-400/10 text-emerald-300"}`}><Icon size={22} /></span><div className="min-w-0 flex-1"><div className="flex justify-between gap-3"><h3 className="font-bold">{title}</h3><span className="text-xs font-bold text-[var(--accent)]">{progress}%</span></div><p className="mt-1 text-xs text-[var(--text-faint)]">{level} · {lessons} lessons</p><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-[var(--surface-raised)]"><div className="h-full rounded-full bg-[var(--accent)]" style={{ width: `${progress}%` }} /></div></div></div></Surface>)}</div>
    <div className="mt-8 grid gap-4 lg:grid-cols-4"><Tool href="/puzzles" icon={Target} title="Puzzle gym" body="Tactics tuned to your level." /><Tool href="/openings" icon={BookOpen} title="Opening trainer" body="Learn ideas, not memorized trees." /><Tool href="/learn/endgames" icon={Landmark} title="Endgame lab" body="Build confidence from bare kings up." /><Tool href="/analysis" icon={BrainCircuit} title="Analysis board" body="Ask better questions of any position." /></div>
  </AppShell>;
}
function Tool({ href, icon: Icon, title, body }: { href: string; icon: typeof GraduationCap; title: string; body: string }) { return <ButtonLink href={href} variant="secondary" className="h-auto items-start justify-start rounded-2xl p-4 text-left"><Icon size={19} className="mt-0.5 shrink-0 text-[var(--accent)]" /><span><span className="block text-sm font-bold">{title}</span><span className="mt-1 block text-xs font-normal leading-5 text-[var(--text-muted)]">{body}</span></span></ButtonLink>; }
