import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { ArrowLeft, CalendarDays, Clock3, LockKeyhole, MessageSquare, ShieldCheck, Sparkles, Trophy, Users } from "lucide-react";
import { AppShell } from "@/components/layout/app-shell";
import { ButtonLink } from "@/components/ui/button";
import { Pill, Surface } from "@/components/ui/surface";
import { clubs } from "../data";

type Props = { params: Promise<{ slug: string }> };
export function generateStaticParams() { return clubs.map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }: Props): Promise<Metadata> { const { slug } = await params; const club = clubs.find((item) => item.slug === slug); return club ? { title: club.name, description: club.description } : { title: "Club not found" }; }

export default async function ClubPage({ params }: Props) { const { slug } = await params; const club = clubs.find((item) => item.slug === slug); if (!club) notFound(); return <AppShell title={club.name} description={club.tagline} actions={<ButtonLink href={`/auth?next=/clubs/${club.slug}`}><Users size={16} />{club.privacy === "Open" ? "Join club" : "Request to join"}</ButtonLink>}>
  <ButtonLink href="/clubs" variant="ghost" size="sm" className="mb-5 px-0"><ArrowLeft size={15} />All clubs</ButtonLink>
  <Surface className="relative overflow-hidden p-6 sm:p-8"><div aria-hidden className="absolute inset-y-0 right-0 w-1/2 opacity-60" style={{ background: `radial-gradient(circle at 80% 10%, ${club.color}2c, transparent 55%)` }} /><div className="relative max-w-3xl"><div className="flex flex-wrap items-center gap-3"><span className="grid size-14 place-items-center rounded-2xl text-base font-black" style={{ color: club.color, backgroundColor: `${club.color}18` }}>{club.initials}</span><div><div className="flex flex-wrap gap-2"><Pill>{club.privacy === "Open" ? <Users size={12} /> : <LockKeyhole size={12} />}{club.privacy}</Pill><Pill>{club.focus}</Pill></div><p className="mt-2 text-xs text-[var(--text-faint)]">{club.members} members · {club.online} around now</p></div></div><p className="mt-6 max-w-2xl text-sm leading-7 text-[var(--text-muted)]">{club.description}</p><div className="mt-6 flex items-center gap-2 text-sm font-bold"><CalendarDays size={17} style={{ color: club.color }} />{club.schedule}</div></div></Surface>
  <div className="mt-6 grid gap-6 lg:grid-cols-[minmax(0,1fr)_330px]"><div className="space-y-5"><Surface className="p-6"><div className="flex items-center justify-between"><div><p className="eyebrow">Club activity</p><h2 className="mt-2 text-xl font-bold">From the room</h2></div><MessageSquare size={19} className="text-[var(--text-faint)]" /></div><div className="mt-5 divide-y divide-[var(--border)]">{club.activity.map((item) => <div key={`${item.actor}-${item.when}`} className="flex gap-3 py-4"><span className="grid size-10 shrink-0 place-items-center rounded-xl text-xl" style={{ color: club.color, backgroundColor: `${club.color}18` }}>♞</span><div><p className="text-sm"><strong>{item.actor}</strong> <span className="text-[var(--text-muted)]">{item.text}</span></p><p className="mt-1 text-xs text-[var(--text-faint)]">{item.when}</p></div></div>)}</div></Surface><Surface className="p-6"><div className="flex items-center gap-3"><Trophy size={20} className="text-orange-300" /><div><p className="font-bold">Next club event</p><p className="text-xs text-[var(--text-muted)]">Member pairing room</p></div></div><div className="mt-5 flex flex-col gap-4 rounded-2xl bg-[var(--surface-soft)] p-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-bold">Club Practice Swiss</p><p className="mt-1 flex items-center gap-2 text-xs text-[var(--text-faint)]"><Clock3 size={13} />10+0 · 5 rounds · schedule pending</p></div><Pill>Members only</Pill></div></Surface></div><aside className="space-y-5"><Surface className="p-5"><ShieldCheck size={20} className="text-emerald-300" /><h2 className="mt-4 font-bold">Room standards</h2><p className="mt-2 text-xs leading-5 text-[var(--text-muted)]">Be generous with learners, label assisted analysis, keep live games assistance-free, and report concerns privately.</p><ButtonLink href="/guidelines" variant="ghost" size="sm" className="mt-3 px-0">Read guidelines</ButtonLink></Surface><Surface className="p-5"><Sparkles size={20} className="text-violet-300" /><h2 className="mt-4 font-bold">Member access</h2><p className="mt-2 text-xs leading-5 text-[var(--text-muted)]">Club membership, messages, and private events require a permanent account. House Players can appear in configured activity or events but do not act as human friends.</p></Surface></aside></div>
  </AppShell>; }
