import type { Metadata } from "next";
import { AlertTriangle, Ban, Check, Flag, Heart, MessagesSquare, Scale, ShieldCheck, UserRoundCheck } from "lucide-react";
import { PublicPage, BetaNotice } from "../features/_components/public-page";
import { ButtonLink } from "@/components/ui/button";
import { Pill, Surface } from "@/components/ui/surface";

export const metadata: Metadata = { title: "Community guidelines", description: "Fair play, respectful communication, safety, reporting, and enforcement guidelines for Busted Minds Chess." };

const good = ["Let your own moves decide competitive games.", "Discuss positions and ideas without attacking the person.", "Use block, mute, and report instead of escalating.", "Respect privacy and ask before sharing private messages.", "Welcome learners and leave room for different skill levels."];
const prohibited = ["Engine or outside assistance in games where it is not allowed.", "Harassment, hate, threats, sexual content, or targeted humiliation.", "Spam, scams, phishing, impersonation, or exposure of private information.", "Rating manipulation, collusion, sandbagging, multi-account abuse, or intentional timeouts.", "Exploiting defects, evading enforcement, or disrupting games and services."];

export default function GuidelinesPage() { return <PublicPage eyebrow="Chess-first, human always" title="Community guidelines" intro="Play the position hard. Treat the person gently. These guidelines apply to profiles, clubs, chat, messages, annotations, event spaces, and every competitive game." aside={<BetaNotice>Safety tooling is still maturing during beta. Blocking and muting give immediate control; reports create a review record and should be reserved for genuine concerns.</BetaNotice>}>
  <div className="grid gap-6 lg:grid-cols-2"><GuideColumn icon={Heart} title="The standard we play toward" tone="emerald" items={good} /><GuideColumn icon={Ban} title="Not welcome here" tone="red" items={prohibited} /></div>
  <section className="mt-16"><div className="flex items-center gap-3"><Scale className="text-[var(--accent)]" size={22} /><h2 className="text-2xl font-bold tracking-[-.03em]">Fair play by context</h2></div><p className="mt-3 max-w-3xl text-sm leading-6 text-[var(--text-muted)]">Tools that make study powerful can make competition meaningless. The interface separates those contexts clearly.</p><div className="mt-6 grid gap-4 md:grid-cols-3"><Context title="Competitive game" label="No assistance" body="No engines, databases, coaches, other players, automation, or analysis boards while the game is active." /><Context title="Casual assisted game" label="Only when labeled" body="Use assistance only when the game setup explicitly allows it and every participant sees the same rule." /><Context title="Analysis & training" label="Tools encouraged" body="Explore lines, request hints, use Stockfish, retry mistakes, and annotate as deeply as you like." /></div></section>
  <section className="mt-16 grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><Surface className="p-6 sm:p-7"><div className="flex items-center gap-3"><Flag className="text-orange-300" size={21} /><h2 className="text-xl font-bold">Report with care</h2></div><div className="mt-5 space-y-4">{[["1","Protect your space","Mute or block if you need the interaction to stop immediately."],["2","Capture the context","Report from the relevant game, message, profile, or event when possible."],["3","Describe observable facts","Explain what happened without guessing motives or organizing public accusations."],["4","Let review happen","Repeated reports do not accelerate review and can obscure the clearest evidence."]].map(([n,title,body]) => <div key={n} className="flex gap-3"><span className="grid size-7 shrink-0 place-items-center rounded-lg bg-orange-400/10 text-xs font-bold text-orange-300">{n}</span><div><p className="text-sm font-bold">{title}</p><p className="mt-1 text-xs leading-5 text-[var(--text-muted)]">{body}</p></div></div>)}</div><ButtonLink href="/contact" variant="secondary" className="mt-6"><MessagesSquare size={16} />Contact safety</ButtonLink></Surface><div className="space-y-5"><Surface className="p-6"><UserRoundCheck size={21} className="text-violet-300" /><h2 className="mt-4 font-bold">House Players have limits</h2><p className="mt-2 text-sm leading-6 text-[var(--text-muted)]">They are fictional system opponents, are identified on profile and game surfaces, use only chess-specific messages, do not accept friendships as people, and never create reports.</p></Surface><Surface className="p-6"><ShieldCheck size={21} className="text-emerald-300" /><h2 className="mt-4 font-bold">Proportionate enforcement</h2><p className="mt-2 text-sm leading-6 text-[var(--text-muted)]">Responses can include education, content removal, chat limits, result or rating correction, event removal, temporary suspension, or account termination. Serious safety threats may require immediate action.</p></Surface></div></section>
  <section className="mt-16 rounded-[2rem] border border-orange-400/20 bg-orange-400/[.05] p-7"><div className="flex gap-4"><AlertTriangle className="mt-1 shrink-0 text-orange-300" /><div><h2 className="text-xl font-bold">A report is not an emergency service</h2><p className="mt-2 text-sm leading-6 text-[var(--text-muted)]">If you or someone else is in immediate danger, contact an appropriate local emergency service. Do not publish private details while seeking help.</p></div></div></section>
  </PublicPage>; }

function GuideColumn({ icon: Icon, title, items, tone }: { icon: typeof Heart; title: string; items: string[]; tone: "emerald" | "red" }) { const color = tone === "emerald" ? "text-emerald-300 bg-emerald-400/10" : "text-red-300 bg-red-400/10"; return <Surface className="p-6 sm:p-7"><span className={`grid size-11 place-items-center rounded-2xl ${color}`}><Icon size={21} /></span><h2 className="mt-5 text-xl font-bold">{title}</h2><div className="mt-5 space-y-3">{items.map((item) => <p key={item} className="flex gap-3 text-sm leading-6 text-[var(--text-muted)]"><Check size={17} className={`mt-1 shrink-0 ${tone === "emerald" ? "text-emerald-300" : "text-red-300"}`} />{item}</p>)}</div></Surface>; }
function Context({ title, label, body }: { title: string; label: string; body: string }) { return <Surface className="p-5"><Pill>{label}</Pill><h3 className="mt-4 font-bold">{title}</h3><p className="mt-2 text-xs leading-5 text-[var(--text-muted)]">{body}</p></Surface>; }
