import type { Metadata } from "next";
import { BookOpen, ChevronRight, Compass, Search, Sparkles } from "lucide-react";
import Link from "next/link";
import { AppShell } from "@/components/layout/app-shell";
import { ButtonLink } from "@/components/ui/button";
import { Pill, Surface } from "@/components/ui/surface";
import { CURATED_OPENINGS } from "@/lib/data/openings";

export const metadata: Metadata = { title: "Opening trainer" };

export default function OpeningsPage() { return <AppShell title="Opening compass" description="A deliberately small explorer focused on plans, landmarks, and lines you can actually remember." actions={<ButtonLink href="/play/ai"><Sparkles size={16} />Practice vs AI</ButtonLink>}><Surface className="p-4"><label className="flex items-center gap-3 rounded-xl bg-[var(--surface-soft)] px-3 py-2.5"><Search size={17} className="text-[var(--text-faint)]" /><input aria-label="Search openings" placeholder="Search by opening, variation, or ECO code" className="w-full bg-transparent text-sm outline-none placeholder:text-[var(--text-faint)]" /></label></Surface><div className="mt-6 grid gap-4 lg:grid-cols-3">{CURATED_OPENINGS.slice(0, 9).map((opening, index) => <Surface key={`${opening.eco}-${opening.name}-${opening.variation}`} className="group p-5"><div className="flex items-center justify-between"><span className="grid size-11 place-items-center rounded-2xl bg-cyan-400/10 text-xl text-cyan-300">{index % 3 === 0 ? "♙" : index % 3 === 1 ? "♘" : "♗"}</span><Pill>{opening.eco}</Pill></div><h2 className="mt-5 text-lg font-bold">{opening.name}</h2><p className="mt-1 text-xs text-[var(--text-muted)]">{opening.variation || "Main line"}</p><p className="mt-4 truncate font-mono text-[10px] text-[var(--text-faint)]">{opening.moves.slice(0, 6).join(" ")}</p><Link href={`/analysis`} className="mt-5 flex items-center justify-between border-t border-[var(--border)] pt-4 text-xs font-bold text-[var(--accent)]">Open explorer<ChevronRight size={15} className="transition group-hover:translate-x-1" /></Link></Surface>)}</div><div className="mt-8 grid gap-5 md:grid-cols-2"><Surface className="p-6"><Compass size={22} className="text-violet-300" /><h2 className="mt-4 text-xl font-bold">Build a repertoire</h2><p className="mt-2 text-sm leading-6 text-[var(--text-muted)]">Choose one response to 1.e4, one to 1.d4, and a White system. We&apos;ll schedule spaced practice from there.</p><ButtonLink href="/auth" variant="secondary" className="mt-5">Save repertoire</ButtonLink></Surface><Surface className="p-6"><BookOpen size={22} className="text-orange-300" /><h2 className="mt-4 text-xl font-bold">Plans before branches</h2><p className="mt-2 text-sm leading-6 text-[var(--text-muted)]">Each lesson starts with pawn breaks, good pieces, and common tactical ideas before asking you to remember moves.</p><ButtonLink href="/learn" variant="secondary" className="mt-5">Opening lessons</ButtonLink></Surface></div></AppShell>; }
