import { ArrowRight, CalendarClock, Filter, Trophy, Users } from "lucide-react";
import { AppShell } from "@/components/layout/app-shell";
import { ButtonLink } from "@/components/ui/button";
import { Pill, Surface } from "@/components/ui/surface";
import { launchTournaments } from "@/lib/data/content";

export default function TournamentsPage() {
  return <AppShell title="Tournaments" description="Structured pressure, friendly rivalries, and a reason to play one more good game." actions={<ButtonLink href="/tournaments/create" variant="secondary"><Trophy size={16} />Create event</ButtonLink>}>
    <Surface className="relative overflow-hidden border-orange-300/15 bg-[linear-gradient(135deg,rgba(255,122,26,.12),var(--surface)_58%)] p-7"><div className="max-w-2xl"><Pill className="border-orange-300/20 text-orange-300">Featured · registration open</Pill><h2 className="mt-4 text-3xl font-bold tracking-[-.04em]">After Hours Arena</h2><p className="mt-3 text-sm leading-6 text-[var(--text-muted)]">Ninety minutes of 3+2 chess. Keep playing, build a streak, and climb while the clock is live.</p><div className="mt-6 flex flex-wrap gap-3"><ButtonLink href="/tournaments/after-hours" className="bg-orange-500 text-white hover:bg-orange-400">Join arena<ArrowRight size={16} /></ButtonLink><Pill><CalendarClock size={13} />Starts in 42 min</Pill><Pill><Users size={13} />12 joined</Pill></div></div><div className="absolute -right-10 -top-7 hidden text-[12rem] leading-none text-orange-300/8 md:block">♜</div></Surface>
    <div className="mt-8 flex items-center justify-between"><h2 className="text-xl font-bold">Upcoming events</h2><button className="icon-button" aria-label="Filter tournaments"><Filter size={18} /></button></div>
    <div className="mt-4 grid gap-4 lg:grid-cols-3">{launchTournaments.map((event) => <Surface key={event.id} className="p-5"><div className="flex items-center justify-between"><Pill>{event.format}</Pill><span className="text-xs font-bold" style={{ color: event.color }}>{event.clock}</span></div><h3 className="mt-5 text-xl font-bold">{event.name}</h3><p className="mt-2 text-sm text-[var(--text-muted)]">{event.starts}</p><div className="mt-5 h-1.5 overflow-hidden rounded-full bg-[var(--surface-raised)]"><div className="h-full rounded-full" style={{ width: `${(event.players / event.cap) * 100}%`, background: event.color }} /></div><div className="mt-3 flex items-center justify-between text-xs text-[var(--text-faint)]"><span>{event.players} of {event.cap} players</span><span>{event.prize}</span></div><ButtonLink href={`/tournaments/${event.id}`} variant="secondary" className="mt-5 w-full">View event</ButtonLink></Surface>)}</div>
    <div className="mt-8 grid gap-4 md:grid-cols-3"><FormatCard title="Arena" body="Play continuously, score streak bonuses, and join late while the arena is open." /><FormatCard title="Swiss" body="A fixed set of rounds pairs you with players on a similar score." /><FormatCard title="Private" body="Invite your club or friends, choose the rules, and run your own event." /></div>
  </AppShell>;
}
function FormatCard({ title, body }: { title: string; body: string }) { return <div className="rounded-2xl border border-dashed border-[var(--border-strong)] p-5"><p className="font-bold">{title}</p><p className="mt-2 text-xs leading-5 text-[var(--text-muted)]">{body}</p></div>; }
