"use client";

import { useState } from "react";
import { Activity, AlertTriangle, BarChart3, Bot, Clock3, Database, ExternalLink, Flag, Gauge, KeyRound, LockKeyhole, Megaphone, PauseCircle, RefreshCw, Search, Server, Settings2, ShieldCheck, ToggleLeft, Trophy, UserCog, Users, Wrench } from "lucide-react";
import { Button, ButtonLink } from "@/components/ui/button";
import { Pill, Surface } from "@/components/ui/surface";
import { housePlayers } from "@/lib/data/content";
import { cn } from "@/lib/utils";

const tabs = [
  { id: "overview", label: "Overview", icon: Activity }, { id: "users", label: "Users", icon: Users }, { id: "house", label: "House Players", icon: Bot }, { id: "moderation", label: "Moderation", icon: Flag }, { id: "platform", label: "Platform", icon: Server },
] as const;
type Tab = typeof tabs[number]["id"];

export function AdminConsole() {
  const [active, setActive] = useState<Tab>("overview");
  return <>
    <Surface className="mb-6 border-orange-400/25 bg-orange-400/[.07] p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-center"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-orange-400/12 text-orange-300"><AlertTriangle size={19} /></span><div className="flex-1"><p className="text-sm font-bold">Safe preview mode</p><p className="mt-1 text-xs leading-5 text-[var(--text-muted)]">Live admin data is not connected on this screen. Example records are labeled “Demo”; operational values show “Not connected.” All mutation controls are disabled to prevent accidental claims or changes.</p></div><Pill className="border-orange-400/20 text-orange-300"><LockKeyhole size={12} />Read-only</Pill></div></Surface>
    <div className="mb-6 overflow-x-auto"><div role="tablist" aria-label="Admin areas" className="inline-flex min-w-full gap-1 rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-1.5 sm:min-w-0">{tabs.map(({ id, label, icon: Icon }) => <button key={id} type="button" role="tab" aria-selected={active === id} onClick={() => setActive(id)} className={cn("flex flex-1 items-center justify-center gap-2 whitespace-nowrap rounded-xl px-3 py-2.5 text-xs font-bold transition sm:flex-none", active === id ? "bg-[var(--accent-soft)] text-[var(--accent)]" : "text-[var(--text-muted)] hover:bg-[var(--surface-hover)] hover:text-[var(--text)]")}><Icon size={15} />{label}</button>)}</div></div>
    {active === "overview" && <Overview />}{active === "users" && <UsersPanel />}{active === "house" && <HousePanel />}{active === "moderation" && <ModerationPanel />}{active === "platform" && <PlatformPanel />}
  </>;
}

function Overview() { return <div className="space-y-6"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Metric icon={Users} label="Active users" value="Not connected" detail="Requires live analytics view" /><Metric icon={BarChart3} label="Games today" value="Not connected" detail="Human / House split" /><Metric icon={Flag} label="Open reports" value="Not connected" detail="Moderation queue" /><Metric icon={Gauge} label="Bot game volume" value="Not connected" detail="Configured window" /></div><div className="grid gap-6 xl:grid-cols-[1.2fr_.8fr]"><Surface className="p-6"><Header icon={Activity} title="Operational pulse" detail="Live series placeholder" /><div className="mt-6 grid h-52 place-items-center rounded-2xl border border-dashed border-[var(--border-strong)] bg-[var(--surface-soft)]"><div className="text-center"><BarChart3 size={26} className="mx-auto text-[var(--text-faint)]" /><p className="mt-3 text-sm font-bold">No telemetry connected</p><p className="mt-1 text-xs text-[var(--text-muted)]">Connect the restricted analytics view to populate game, queue, and error trends.</p></div></div></Surface><Surface className="p-6"><Header icon={Clock3} title="Operations queue" detail="Safe status view" /><div className="mt-5 space-y-3"><QueueItem title="Report review" status="Not connected" /><QueueItem title="Abandoned-game cleanup" status="Request-driven" /><QueueItem title="Rating corrections" status="No live count" /><QueueItem title="Tournament progression" status="No live count" /></div></Surface></div><Surface className="p-6"><Header icon={ShieldCheck} title="Admin boundaries" detail="Required before enabling mutations" /><div className="mt-5 grid gap-3 md:grid-cols-3"><Boundary title="Server-controlled roles" body="Admin and moderator permissions must come from protected role tables, never editable profile fields." /><Boundary title="Audited mutations" body="Every sensitive action needs actor, target, reason, request identifier, and timestamp." /><Boundary title="Two-step risk controls" body="Bans, rating corrections, maintenance mode, and bot-wide changes need explicit confirmation." /></div></Surface></div>; }

function UsersPanel() { const demo = [{ name: "ExamplePlayer", email: "example@invalid.test", role: "Member", state: "Active" }, { name: "ReviewExample", email: "review@invalid.test", role: "Member", state: "Restricted" }, { name: "ModeratorExample", email: "moderator@invalid.test", role: "Moderator", state: "Active" }]; return <div className="space-y-6"><Surface className="p-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-center"><Header icon={UserCog} title="User management" detail="Demo records only" /><label className="sm:ml-auto flex h-10 items-center gap-2 rounded-xl border border-[var(--border)] bg-[var(--surface-soft)] px-3"><Search size={15} className="text-[var(--text-faint)]" /><span className="sr-only">Search users</span><input disabled placeholder="Live search unavailable" className="w-48 bg-transparent text-xs outline-none disabled:cursor-not-allowed" /></label></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead><tr className="border-b border-[var(--border)] text-[10px] uppercase tracking-wider text-[var(--text-faint)]"><th className="px-3 py-3">User</th><th className="px-3 py-3">Role</th><th className="px-3 py-3">Account state</th><th className="px-3 py-3">Signals</th><th className="px-3 py-3 text-right">Action</th></tr></thead><tbody>{demo.map((user) => <tr key={user.email} className="border-b border-[var(--border)] last:border-0"><td className="px-3 py-4"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-xl bg-[var(--surface-raised)] text-lg">♟</span><div><p className="font-bold">{user.name} <span className="ml-1 text-[9px] uppercase text-orange-300">Demo</span></p><p className="mt-0.5 text-xs text-[var(--text-faint)]">{user.email}</p></div></div></td><td className="px-3 py-4"><Pill>{user.role}</Pill></td><td className="px-3 py-4 text-[var(--text-muted)]">{user.state}</td><td className="px-3 py-4 text-[var(--text-faint)]">No live data</td><td className="px-3 py-4 text-right"><Button disabled variant="ghost" size="sm">Inspect</Button></td></tr>)}</tbody></table></div></Surface><div className="grid gap-4 md:grid-cols-3"><AdminAction icon={KeyRound} title="Role assignment" body="Requires admin re-authentication and an immutable audit event." /><AdminAction icon={PauseCircle} title="Account restriction" body="Choose scope, duration, policy basis, and internal note before applying." /><AdminAction icon={RefreshCw} title="Guest upgrades" body="Inspect unresolved ownership transfers without exposing credentials." /></div></div>; }

function HousePanel() { return <div className="space-y-6"><Surface className="p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-center"><Header icon={Bot} title="House-player controls" detail="Profiles from launch configuration" /><div className="sm:ml-auto flex gap-2"><Button disabled variant="secondary" size="sm">Calibrate</Button><Button disabled size="sm">Add profile</Button></div></div><div className="mt-5 grid gap-4 lg:grid-cols-2">{housePlayers.map((player) => <div key={player.id} className="rounded-2xl border border-[var(--border)] bg-[var(--surface-soft)] p-4"><div className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-xl text-2xl" style={{ color: player.color, backgroundColor: `${player.color}18` }}>♞</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{player.name}</p><p className="text-xs text-[var(--text-faint)]">{player.rating} · {player.style} · level {player.level}</p></div><input aria-label={`${player.name} enabled`} type="checkbox" className="toggle" checked disabled readOnly /></div><div className="mt-4 grid grid-cols-2 gap-2"><Mini label="Availability" value="Not connected" /><Mini label="Games in window" value="Not connected" /><Mini label="Matchmaking" value="Configured server-side" /><Mini label="Tournament access" value="Policy-controlled" /></div></div>)}</div></Surface><div className="grid gap-5 xl:grid-cols-2"><Surface className="p-6"><Header icon={Settings2} title="Matchmaking fallback" detail="Disabled preview controls" /><div className="mt-5 space-y-5"><Slider label="Wait before offer" value="Configuration unavailable" /><Slider label="Rating tolerance" value="Configuration unavailable" /><DisabledToggle label="Bullet fallback" /><DisabledToggle label="Blitz fallback" /><DisabledToggle label="Rapid fallback" /><DisabledToggle label="Classical fallback" /></div></Surface><Surface className="p-6"><Header icon={Trophy} title="Competition policy" detail="Disabled preview controls" /><div className="mt-5 space-y-3"><DisabledToggle label="Allow casual bot games" /><DisabledToggle label="Allow fixed-strength rated bots" /><DisabledToggle label="Fill tournament open places" /><DisabledToggle label="Include bots in global rankings" /><DisabledToggle label="Include bots in seasonal rankings" /></div><p className="mt-5 text-xs leading-5 text-[var(--text-faint)]">Rated bot play must use fixed, calibrated profiles and preserve the human-versus-system distinction in results and rating history.</p></Surface></div></div>; }

function ModerationPanel() { const demos = [{ type: "Chat conduct", subject: "ExamplePlayer", age: "Demo", severity: "Medium" }, { type: "Fair play", subject: "ReviewExample", age: "Demo", severity: "High" }]; return <div className="space-y-6"><div className="grid gap-4 md:grid-cols-3"><Metric icon={Flag} label="Unassigned reports" value="Not connected" detail="Live moderation view required" /><Metric icon={Clock3} label="Oldest report" value="Not connected" detail="No SLA inferred" /><Metric icon={ShieldCheck} label="Actions today" value="Not connected" detail="Audit log required" /></div><Surface className="p-6"><Header icon={Flag} title="Report review queue" detail="Demonstration rows" /><div className="mt-5 space-y-3">{demos.map((report, index) => <div key={`${report.subject}-${index}`} className="grid gap-3 rounded-2xl border border-[var(--border)] bg-[var(--surface-soft)] p-4 sm:grid-cols-[1fr_1fr_auto_auto] sm:items-center"><div><p className="text-sm font-bold">{report.type} <span className="ml-1 text-[9px] uppercase text-orange-300">Demo</span></p><p className="mt-1 text-xs text-[var(--text-faint)]">Evidence is intentionally unavailable</p></div><p className="text-sm text-[var(--text-muted)]">{report.subject}</p><Pill>{report.severity}</Pill><Button disabled variant="secondary" size="sm">Review</Button></div>)}</div></Surface><div className="grid gap-4 md:grid-cols-3"><AdminAction icon={Flag} title="Reports" body="Preserve the original context, reporter visibility rules, and review history." /><AdminAction icon={ShieldCheck} title="Game inspection" body="Show authoritative moves, clocks, versions, identities, and integrity signals." /><AdminAction icon={Wrench} title="Corrections" body="Require a reason and atomic server mutation for results or ratings." /></div></div>; }

function PlatformPanel() { return <div className="space-y-6"><div className="grid gap-6 xl:grid-cols-2"><Surface className="p-6"><div className="flex items-center gap-3"><Header icon={Server} title="Health checks" detail="No check executed on this screen" /><ButtonLink href="/api/health" target="_blank" rel="noreferrer" variant="secondary" size="sm" className="ml-auto">Open endpoint<ExternalLink size={13} /></ButtonLink></div><div className="mt-5 space-y-3"><Health label="Application" /><Health label="Supabase connection" /><Health label="Server credentials" /><Health label="Database migrations" /><Health label="Stockfish asset" /></div></Surface><Surface className="p-6"><Header icon={Database} title="Usage & quotas" detail="Telemetry not connected" /><div className="mt-5 space-y-5"><Quota label="Database storage" /><Quota label="Realtime connections" /><Quota label="Function execution" /><Quota label="Authentication email" /><Quota label="Storage bandwidth" /></div><p className="mt-5 text-xs leading-5 text-[var(--text-faint)]">Display provider-reported usage windows and plan limits here; never estimate remaining quota from client activity alone.</p></Surface></div><div className="grid gap-6 xl:grid-cols-[1fr_1fr]"><Surface className="p-6"><Header icon={ToggleLeft} title="Feature flags" detail="Example configuration only" /><div className="mt-5 space-y-3">{["Public matchmaking", "Tournament creation", "Club discovery", "Direct messages", "Saved analysis", "Low-population feed sections"].map((label) => <div key={label} className="flex items-center justify-between rounded-xl bg-[var(--surface-soft)] px-4 py-3"><div><p className="text-sm font-bold">{label}</p><p className="text-[10px] uppercase tracking-wider text-orange-300">Demo flag</p></div><input aria-label={label} type="checkbox" className="toggle" disabled /></div>)}</div></Surface><div className="space-y-6"><Surface className="p-6"><Header icon={Megaphone} title="Announcement banner" detail="Disabled preview" /><textarea disabled rows={3} placeholder="Live announcement text is not loaded" className="mt-5 w-full resize-none rounded-xl border border-[var(--border)] bg-[var(--surface-soft)] p-3 text-sm outline-none" /><div className="mt-3 flex justify-end"><Button disabled size="sm">Publish</Button></div></Surface><Surface className="border-red-400/15 bg-red-400/[.04] p-6"><Header icon={Wrench} title="Maintenance mode" detail="High-impact control" /><p className="mt-4 text-xs leading-5 text-[var(--text-muted)]">Enabling maintenance should require confirmation, an operator reason, an end condition, and an audit record. Active games need a separately reviewed handling plan.</p><Button disabled variant="danger" className="mt-5"><PauseCircle size={16} />Enable maintenance</Button></Surface></div></div></div>; }

function Header({ icon: Icon, title, detail }: { icon: typeof Activity; title: string; detail: string }) { return <div className="flex min-w-0 items-center gap-3"><span className="grid size-9 shrink-0 place-items-center rounded-xl bg-[var(--accent-soft)] text-[var(--accent)]"><Icon size={17} /></span><div className="min-w-0"><h2 className="truncate font-bold">{title}</h2><p className="truncate text-xs text-[var(--text-faint)]">{detail}</p></div></div>; }
function Metric({ icon: Icon, label, value, detail }: { icon: typeof Users; label: string; value: string; detail: string }) { return <Surface className="p-5"><div className="flex items-center justify-between"><Icon size={18} className="text-[var(--accent)]" /><Pill>Preview</Pill></div><p className="mt-5 text-xs font-bold text-[var(--text-faint)]">{label}</p><p className="mt-2 text-lg font-bold">{value}</p><p className="mt-1 text-[10px] text-[var(--text-faint)]">{detail}</p></Surface>; }
function QueueItem({ title, status }: { title: string; status: string }) { return <div className="flex items-center justify-between gap-3 rounded-xl bg-[var(--surface-soft)] px-4 py-3"><p className="text-sm font-bold">{title}</p><span className="text-xs text-[var(--text-faint)]">{status}</span></div>; }
function Boundary({ title, body }: { title: string; body: string }) { return <div className="rounded-2xl bg-[var(--surface-soft)] p-4"><p className="text-sm font-bold">{title}</p><p className="mt-2 text-xs leading-5 text-[var(--text-muted)]">{body}</p></div>; }
function AdminAction({ icon: Icon, title, body }: { icon: typeof Flag; title: string; body: string }) { return <Surface className="p-5"><Icon size={19} className="text-[var(--accent)]" /><p className="mt-4 text-sm font-bold">{title}</p><p className="mt-2 text-xs leading-5 text-[var(--text-muted)]">{body}</p><Button disabled variant="ghost" size="sm" className="mt-3 px-0">Configure</Button></Surface>; }
function Mini({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-[var(--surface)] p-3"><p className="text-[9px] font-bold uppercase tracking-wider text-[var(--text-faint)]">{label}</p><p className="mt-1 text-xs font-bold">{value}</p></div>; }
function Slider({ label, value }: { label: string; value: string }) { return <label className="block"><span className="flex justify-between gap-3 text-xs"><strong>{label}</strong><span className="text-[var(--text-faint)]">{value}</span></span><input disabled type="range" className="mt-2 w-full accent-[var(--accent)]" /></label>; }
function DisabledToggle({ label }: { label: string }) { return <label className="flex items-center justify-between gap-3 rounded-xl bg-[var(--surface-soft)] px-4 py-3"><span className="text-sm font-bold">{label}</span><input aria-label={label} type="checkbox" className="toggle" disabled /></label>; }
function Health({ label }: { label: string }) { return <div className="flex items-center justify-between gap-3 rounded-xl bg-[var(--surface-soft)] px-4 py-3"><p className="text-sm font-bold">{label}</p><Pill>Not checked</Pill></div>; }
function Quota({ label }: { label: string }) { return <div><div className="mb-2 flex justify-between text-xs"><strong>{label}</strong><span className="text-[var(--text-faint)]">Not connected</span></div><div className="h-2 overflow-hidden rounded-full border border-dashed border-[var(--border-strong)] bg-[var(--surface-soft)]" /></div>; }
