import type { Metadata } from "next";
import Link from "next/link";
import { PublicPage, PolicyLayout, ProseList } from "../features/_components/public-page";

export const metadata: Metadata = { title: "Terms of service", description: "The rules for accounts, play, competitions, content, acceptable use, beta availability, and disputes on Busted Minds Chess." };
const updated = "July 21, 2026";

export default function TermsPage() {
  const sections = [
    { id: "agreement", title: "Agreement and eligibility", body: <><p>These Terms govern your use of Busted Minds Chess. By accessing or using the service, you agree to these Terms and the <Link href="/guidelines" className="font-bold text-[var(--accent)] hover:underline">Community Guidelines</Link>. If you do not agree, do not use the service.</p><p>You must be at least 13, or the higher minimum age required in your country without guardian authorization, and legally capable of entering this agreement. If you use the service for an organization, you confirm that you can bind it.</p></> },
    { id: "beta", title: "Public beta and free access", body: <><p>The service is in public beta. Features can be incomplete, changed, rate-limited, paused, or removed as reliability and fair-play systems mature. We may schedule maintenance or make urgent changes without advance notice when needed for security.</p><p>A useful free experience is a core design goal, including Local and Vs AI play. We do not promise that every feature will always be free or available. Any future paid feature will disclose its price and terms before purchase; progression purchases, if introduced, will not change legal chess moves or competitive results.</p></> },
    { id: "accounts", title: "Accounts", body: <ProseList><li>Provide accurate account information and keep your sign-in method secure.</li><li>Do not share accounts, sell access, evade a suspension, or create accounts to manipulate ratings or rewards.</li><li>You are responsible for activity performed through your account unless you report unauthorized access promptly.</li><li>Roles, bans, house-player status, ratings, and other authoritative fields are controlled by the service and may not be altered directly.</li></ProseList> },
    { id: "play", title: "Games, ratings, and events", body: <><p>Online moves, clocks, results, pairings, and rating changes are decided by authoritative server records. The display on your device can be provisional while a request is validated. We may correct a clear technical error, reverse manipulated ratings, adjudicate a disrupted event, or void a game when integrity requires it.</p><p>House Players are fictional, system-controlled opponents and are labeled as such. They may participate in configured queues, demonstrations, or events. Availability, strength, response time, rating eligibility, and ranking inclusion are operational settings, not guarantees.</p></> },
    { id: "fair-play", title: "Fair play", body: <><p>Do not use engine assistance, opening databases, outside help, automation, multiple accounts, intentional disconnects, sandbagging, collusion, or exploit abuse in games or events where such help is prohibited. Analysis tools are welcome in designated analysis, training, local, or computer-play contexts.</p><p>We may use game patterns, technical records, reports, and human review to investigate integrity. Enforcement can include warnings, result adjustments, rating corrections, feature limits, event removal, suspension, or termination. Automated signals should inform rather than be the sole basis for serious action where review is practical.</p></> },
    { id: "conduct", title: "Acceptable use", body: <ProseList><li>Keep communication chess-focused and follow the Community Guidelines.</li><li>Do not harass, threaten, impersonate, spam, phish, expose private information, or upload unlawful content.</li><li>Do not probe, overload, bypass, scrape, reverse engineer contrary to law, or interfere with security or service limits.</li><li>Do not submit malware, secrets, sensitive identity documents, or content that infringes others’ rights.</li></ProseList> },
    { id: "content", title: "Your content and our materials", body: <><p>You retain ownership of content you create. You grant us a non-exclusive, worldwide, royalty-free license to host, reproduce, display, format, and distribute it only as needed to operate, secure, improve, and promote the service according to your visibility choices. This license ends when content is deleted, except for lawful retention, cached public shares, and content incorporated into another user’s permitted activity.</p><p>The Busted Minds Chess name, original design, logos, curated lessons, and service code are protected by applicable rights. Third-party chess libraries, icons, and engine assets remain under their respective open-source licenses; see <Link href="/licenses" className="font-bold text-[var(--accent)] hover:underline">Licenses</Link>.</p></> },
    { id: "moderation", title: "Moderation and enforcement", body: <p>We may remove content, restrict features, preserve evidence, or suspend accounts to enforce these Terms, protect people or systems, comply with law, or manage material risk. We aim for proportionate action and may offer a review channel, but immediate restrictions may be necessary. House Players do not file reports or accept social relationships as though they were humans.</p> },
    { id: "availability", title: "Availability and changes", body: <p>We strive for reliable service but do not guarantee uninterrupted access, particular opponents, event participation, saved analysis depth, response time, or compatibility with every device. Free-tier resource limits and provider incidents can affect availability. You should export or keep copies of content that is especially important to you.</p> },
    { id: "termination", title: "Ending use", body: <p>You may stop using the service and request account deletion. We may suspend or terminate access for material or repeated violations, security risk, legal requirements, or discontinuation. Provisions concerning ownership, disclaimers, liability, enforcement records, and disputes survive where their nature requires it.</p> },
    { id: "disclaimers", title: "Disclaimers", body: <p>To the fullest extent permitted by law, the beta service is provided “as is” and “as available,” without implied warranties of uninterrupted operation, fitness for a particular purpose, non-infringement, or error-free analysis. Chess engine evaluations and learning explanations are informational and can be incomplete or wrong. Nothing in these Terms excludes a warranty that cannot legally be excluded.</p> },
    { id: "liability", title: "Limitation of liability", body: <p>To the fullest extent permitted by law, Busted Minds Chess and its operators will not be liable for indirect, incidental, special, consequential, or punitive loss, or for lost data, opportunity, goodwill, or profits arising from use of the free beta service. Where liability cannot be excluded, it is limited to the greater of the amount you paid us for the relevant service in the prior 12 months or USD 50. These limits do not apply where prohibited or to liability that law does not allow us to limit.</p> },
    { id: "law", title: "Disputes and applicable law", body: <p>Before filing a formal claim, contact us and give both sides 30 days to attempt an informal resolution. Applicable law and forum depend on the operator’s legally registered location and mandatory consumer protections where you live; no part of these Terms removes rights that cannot be waived. A definitive jurisdiction clause will be added before any paid offering where required.</p> },
    { id: "changes", title: "Changes and contact", body: <><p>We may update these Terms as the beta evolves. Material changes will receive reasonable notice when practical and a new effective date. If you do not accept an update, stop using the service before it takes effect.</p><p>Questions can be sent through the <Link href="/contact" className="font-bold text-[var(--accent)] hover:underline">Contact page</Link>.</p></> },
  ];
  return <PublicPage eyebrow="The rules around the board" title="Terms of service" intro="These terms protect fair games, thoughtful community spaces, and a sustainable public beta. The plain-language summary helps, but the complete terms below are the agreement." ><PolicyLayout updated={updated} summary={<p>Play fairly, protect your account, respect other people, and use assistance only where it is allowed. The beta and its free features can change, and serious abuse can lead to restrictions.</p>} sections={sections} /></PublicPage>;
}
