import type { Metadata } from "next";
import Link from "next/link";
import { PublicPage, PolicyLayout, ProseList } from "../features/_components/public-page";

export const metadata: Metadata = { title: "Privacy policy", description: "How Busted Minds Chess collects, uses, stores, and protects account, game, social, technical, and feedback data." };
const updated = "July 21, 2026";

export default function PrivacyPage() {
  const sections = [
    { id: "scope", title: "Scope and our role", body: <><p>This policy explains how Busted Minds Chess (“we”, “us”, or “the service”) handles personal information when you use the website, installed web app, games, learning tools, community features, or support channels. It does not govern third-party sites you choose to visit.</p><p>The service is in public beta. Features and data flows may change; we will update this notice when a material change affects how information is handled.</p></> },
    { id: "collect", title: "Information we collect", body: <><ProseList><li><strong className="text-[var(--text)]">Account data:</strong> email address, display name, avatar, authentication provider identifiers, account status, and server-controlled roles.</li><li><strong className="text-[var(--text)]">Chess data:</strong> moves, positions, clocks, results, ratings, pairings, tournament entries, saved analysis summaries, achievements, and fair-play or integrity metadata.</li><li><strong className="text-[var(--text)]">Social content:</strong> profiles, club membership, friend and block relationships, messages, reactions, reports, and moderation history.</li><li><strong className="text-[var(--text)]">Technical data:</strong> IP address, timestamps, browser and device characteristics, request identifiers, security events, error details, and limited usage metrics.</li><li><strong className="text-[var(--text)]">What you send us:</strong> feedback, support messages, and any contact details or links you choose to include.</li></ProseList><p>Google sign-in requests only OpenID, email, and basic profile information. We do not request access to contacts, Drive, Calendar, or other unrelated Google data.</p></> },
    { id: "local", title: "Local play and browser analysis", body: <><p>Local Hotseat and direct Vs AI play run primarily on your device. They do not use Supabase resources or become part of your cloud game history unless you explicitly save eligible game or progress data.</p><p>Stockfish analysis runs in a browser Web Worker. Large engine lines and search output are not persisted by default. If you save an analysis, the service may keep a compact summary and your annotations rather than the full engine computation.</p><p>Offline preferences and unsaved games may be stored in browser storage on your device. Clearing site data can remove them.</p></> },
    { id: "use", title: "How and why we use information", body: <ProseList><li>Provide authentication, games, clocks, matchmaking, ratings, tournaments, learning, social features, and account recovery.</li><li>Validate legal moves, prevent duplicate mutations, enforce permissions, investigate abuse, and protect competitive integrity.</li><li>Operate, debug, measure, and improve the service, including free-tier capacity planning.</li><li>Respond to support, feedback, privacy, and safety requests.</li><li>Meet legal obligations and establish, exercise, or defend legal claims where necessary.</li></ProseList> },
    { id: "bases", title: "Legal bases", body: <p>Depending on where you live, we rely on performance of our agreement to provide requested features, legitimate interests in security and service improvement, consent where the interface asks for it, and compliance with legal obligations. You may withdraw consent for future processing where consent is the basis; this does not undo lawful earlier processing.</p> },
    { id: "sharing", title: "Service providers and disclosure", body: <><p>We use carefully scoped providers to operate the service: Vercel for application hosting and functions; Supabase for database, authentication, Realtime, and storage; Resend through configured Supabase SMTP for authentication email delivery; and Google when you choose Google sign-in. These providers process information under their own terms and data-protection commitments.</p><p>We may disclose information when required by law, to protect users or the service, in a business reorganization with appropriate safeguards, or with your direction. We do not sell personal information or use game data for third-party behavioral advertising.</p></> },
    { id: "public", title: "Public and social information", body: <p>Your display name, avatar, ratings, public games, achievements, and profile details may be visible to others. Tournament standings, club activity, and shared annotations may also be public according to their settings. Direct messages, blocks, reports, email addresses, and moderation notes are not public. Review visibility controls before posting or sharing a game link.</p> },
    { id: "retention", title: "Retention", body: <><p>We keep account and persistent game data while your account is active and as needed to provide features you requested. Temporary, abandoned, or anonymous records may be removed sooner through request-driven or scheduled cleanup. Security, moderation, transaction-integrity, and legal records may be retained longer where reasonably necessary.</p><p>Deletion from live systems does not always remove data immediately from encrypted backups; backup copies age out on provider schedules and are not used to restore an individual deleted record except during disaster recovery.</p></> },
    { id: "security", title: "Security", body: <p>We use encrypted transport, restrictive database access policies, server-side authorization, protected secrets, rate limits, audit-oriented identifiers, and authoritative move validation. No internet service can guarantee absolute security. Use a unique password, protect your sign-in method, and report suspected account compromise promptly.</p> },
    { id: "choices", title: "Your choices and rights", body: <><p>You can edit eligible profile fields, change display preferences, avoid cloud saving for local modes, block or mute users, and disconnect by signing out. Depending on local law, you may request access, correction, deletion, restriction, portability, or objection, and may complain to your data-protection authority.</p><p>Send a request through the <Link href="/contact" className="font-bold text-[var(--accent)] hover:underline">contact form</Link> using the email associated with your account. We may need to verify identity without asking for your password. Some records must be retained for security, legal, or rating-integrity reasons.</p></> },
    { id: "cookies", title: "Cookies and local storage", body: <p>Essential cookies keep authentication sessions secure. Browser storage supports preferences, PWA operation, offline games, and local engine state. We do not require third-party advertising cookies. If optional analytics are introduced, consent choices will be presented where required.</p> },
    { id: "children", title: "Children", body: <p>The service is not directed to children under 13, or a higher minimum age required by local law without appropriate guardian authorization. If you believe a child provided personal information contrary to this rule, contact us so we can investigate and delete it where required.</p> },
    { id: "international", title: "International processing", body: <p>Our providers may process information in countries other than your own. Where required, we use provider commitments and legally recognized transfer safeguards. Provider locations and subprocessors can change; their current documentation contains the most precise infrastructure information.</p> },
    { id: "contact", title: "Contact and changes", body: <><p>Questions or privacy requests can be submitted through the <Link href="/contact" className="font-bold text-[var(--accent)] hover:underline">Contact page</Link>. Choose “Privacy request” so it can be routed correctly.</p><p>Material changes will be reflected by a new effective date and, when appropriate, an in-product notice. Continuing to use the service after an effective update means the new policy applies to future use, subject to rights provided by law.</p></> },
  ];
  return <PublicPage eyebrow="Your data, explained" title="Privacy policy" intro="We collect what is needed to run trustworthy chess, keep browser-only play local by default, and give you meaningful choices about what becomes persistent." ><PolicyLayout updated={updated} summary={<p>Local and direct AI games stay on your device unless you save. Online play needs compact game and account data. We use service providers—not data brokers—and do not sell personal information.</p>} sections={sections} /></PublicPage>;
}
