import type { Metadata } from "next";
import { ArrowRight, BarChart3, Bookmark, CloudOff, Crown, LockKeyhole, Settings2, Sparkles, Trophy, UserRound } from "lucide-react";
import { AppShell } from "@/components/layout/app-shell";
import { ButtonLink } from "@/components/ui/button";
import { Pill, Surface } from "@/components/ui/surface";

export const metadata: Metadata = { title: "Your chess profile", description: "Manage your public chess identity, ratings, saved games, achievements, and privacy settings." };

export default function ProfilePage() { return <AppShell title="Your profile" description="Your public chess identity, progress, and the controls that decide what others can see." actions={<ButtonLink href="/auth?next=/profile"><UserRound size={16} />Sign in to continue</ButtonLink>}>
  <Surface className="relative overflow-hidden p-6 sm:p-8"><div className="absolute -right-16 -top-16 size-64 rounded-full bg-cyan-400/10 blur-3xl" /><div className="relative grid gap-7 lg:grid-cols-[auto_minmax(0,1fr)_auto] lg:items-center"><div className="grid size-24 place-items-center rounded-[1.7rem] border border-cyan-300/20 bg-[linear-gradient(145deg,rgba(25,198,237,.2),rgba(25,198,237,.04))] text-5xl">♙</div><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-2xl font-bold">Guest player</h2><Pill><CloudOff size={12} />This device only</Pill></div><p className="mt-3 max-w-2xl text-sm leading-6 text-[var(--text-muted)]">You can play Local and Vs AI immediately. Guest games and preferences may remain in browser storage, but they are not a permanent cloud profile and can disappear when site data is cleared.</p></div><ButtonLink href="/auth?next=/profile" variant="secondary">Create permanent profile<ArrowRight size={16} /></ButtonLink></div></Surface>
  <div className="mt-6 grid gap-6 lg:grid-cols-[minmax(0,1fr)_340px]"><div className="space-y-6"><Surface className="p-6"><p className="eyebrow">Unlock with an account</p><h2 className="mt-2 text-xl font-bold">Keep the story behind your games</h2><div className="mt-5 grid gap-3 sm:grid-cols-2">{[[BarChart3,"Separate ratings","Track bullet, blitz, rapid, and classical progress."],[Bookmark,"Saved games","Favorite, annotate, search, and share your game archive."],[Trophy,"Events & badges","Join tournaments, earn achievements, and keep streaks."],[Crown,"Clubs & friends","Challenge players, join clubs, and control social access."]].map(([Icon,title,body]) => { const FeatureIcon = Icon as typeof BarChart3; return <div key={title as string} className="rounded-2xl bg-[var(--surface-soft)] p-4"><FeatureIcon size={18} className="text-[var(--accent)]" /><p className="mt-3 text-sm font-bold">{title as string}</p><p className="mt-1 text-xs leading-5 text-[var(--text-muted)]">{body as string}</p></div>; })}</div></Surface><Surface className="p-6"><div className="flex items-center gap-3"><Sparkles size={20} className="text-violet-300" /><h2 className="font-bold">Guest upgrade</h2></div><p className="mt-3 text-sm leading-6 text-[var(--text-muted)]">When the upgrade flow finds eligible guest games or local progress, it will show exactly what can be attached to the new account before you confirm. Sign-in never silently publishes a private local game.</p></Surface></div><aside className="space-y-5"><Surface className="p-5"><Settings2 size={20} className="text-[var(--accent)]" /><h2 className="mt-4 font-bold">Profile controls</h2><p className="mt-2 text-xs leading-5 text-[var(--text-muted)]">Permanent profiles can manage display name, avatar, bio, game visibility, challenge preferences, blocks, and communication settings.</p><ButtonLink href="/auth?next=/profile" variant="ghost" size="sm" className="mt-3 px-0">Sign in to manage</ButtonLink></Surface><Surface className="border-emerald-400/15 bg-emerald-400/[.05] p-5"><LockKeyhole size={20} className="text-emerald-300" /><h2 className="mt-4 font-bold">Private stays private</h2><p className="mt-2 text-xs leading-5 text-[var(--text-muted)]">Email, blocks, direct messages, reports, and moderation records are never shown on a public profile.</p></Surface></aside></div>
  </AppShell>; }
