import { ArrowRight, Bolt, BrainCircuit, CalendarDays, Flame, History, Medal, Puzzle, Sparkles, Target, TrendingUp, Trophy, Users } from "lucide-react";
import { AppShell } from "@/components/layout/app-shell";
import { ButtonLink } from "@/components/ui/button";
import { Pill, Surface } from "@/components/ui/surface";
import { dailyMission, housePlayers, learningTracks } from "@/lib/data/content";
import { NovaSprite } from "@/components/mascot/nova-sprite";

export default function DashboardPage() {
  return (
    <AppShell title="Good evening, challenger." description="A fresh board, one useful lesson, and your next milestone are all within reach." actions={<ButtonLink href="/play/online"><Bolt size={17} fill="currentColor" />Quick play</ButtonLink>}>
      <div className="grid gap-5 xl:grid-cols-[1.4fr_.8fr]">
        <div className="space-y-5">
          <Surface className="relative overflow-hidden p-6 sm:p-8">
            <div className="absolute -right-16 -top-20 size-72 rounded-full bg-cyan-400/10 blur-3xl" />
            <div className="relative grid gap-8 md:grid-cols-[1fr_auto] md:items-center">
              <div><Pill className="text-cyan-200"><Sparkles size={13} />Start here</Pill><h2 className="mt-4 max-w-lg text-3xl font-bold tracking-[-.045em] sm:text-4xl">A balanced 10-minute game, matched in seconds.</h2><p className="mt-3 max-w-xl text-sm leading-6 text-[var(--text-muted)]">We&apos;ll look for a player near your level. If the pool is quiet, a compatible house player can step in.</p><div className="mt-6 flex flex-wrap gap-3"><ButtonLink href="/play/online">Find an opponent<ArrowRight size={16} /></ButtonLink><ButtonLink href="/play" variant="secondary">Change settings</ButtonLink></div></div>
              <div className="mx-auto grid size-40 place-items-center overflow-hidden rounded-[2rem] border border-cyan-300/15 bg-[radial-gradient(circle,rgba(25,198,237,.2),rgba(25,198,237,.03))] shadow-inner"><NovaSprite pose="wave" className="size-44" /></div>
            </div>
          </Surface>
          <div className="grid gap-5 lg:grid-cols-2">
            <Surface className="p-6"><div className="flex items-center justify-between"><div><p className="eyebrow text-orange-300">Daily puzzle</p><h3 className="mt-2 text-xl font-bold">{dailyMission.title}</h3></div><div className="grid size-11 place-items-center rounded-2xl bg-orange-400/10 text-orange-300"><Target size={21} /></div></div><p className="mt-3 text-sm leading-6 text-[var(--text-muted)]">{dailyMission.description}</p><div className="mt-6 flex items-center gap-3"><ButtonLink href="/puzzles" className="bg-orange-500 text-white hover:bg-orange-400">Solve now</ButtonLink><Pill><Flame size={13} className="text-orange-300" />{dailyMission.streak} days</Pill></div></Surface>
            <Surface className="p-6"><div className="flex items-center justify-between"><div><p className="eyebrow">Your rapid rating</p><h3 className="mt-2 text-4xl font-bold">1,248 <span className="text-sm font-semibold text-emerald-400">+38</span></h3></div><TrendingUp size={28} className="text-emerald-400" /></div><div className="mt-6 flex h-16 items-end gap-1" aria-label="Rating trend over seven games">{[32,45,38,51,48,62,73,68,82,91].map((height, i) => <span key={i} className="flex-1 rounded-sm bg-gradient-to-t from-cyan-600 to-cyan-300" style={{ height: `${height}%`, opacity: .35 + i * .06 }} />)}</div><div className="mt-4 flex justify-between text-xs text-[var(--text-faint)]"><span>10 games</span><LinkWithArrow href="/games">View history</LinkWithArrow></div></Surface>
          </div>
          <Surface className="p-6"><div className="flex items-center justify-between"><div><p className="eyebrow">Continue learning</p><h3 className="mt-2 text-xl font-bold">Your study plan</h3></div><ButtonLink href="/learn" variant="ghost" size="sm">All lessons<ArrowRight size={15} /></ButtonLink></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{learningTracks.slice(0, 2).map(({ title, lessons, progress, icon: Icon, color }) => <div key={title} className="rounded-2xl border border-[var(--border)] bg-[var(--surface-soft)] p-4"><div className="flex items-start gap-3"><span className={`grid size-10 shrink-0 place-items-center rounded-xl ${color === "orange" ? "bg-orange-400/10 text-orange-300" : "bg-cyan-400/10 text-cyan-300"}`}><Icon size={18} /></span><div className="min-w-0"><p className="text-sm font-bold">{title}</p><p className="mt-1 text-xs text-[var(--text-faint)]">{lessons} lessons · {progress}% complete</p></div></div><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-[var(--surface-raised)]"><div className="h-full rounded-full bg-[var(--accent)]" style={{ width: `${progress}%` }} /></div></div>)}</div></Surface>
        </div>
        <div className="space-y-5">
          <Surface className="p-5"><div className="flex items-center justify-between"><h3 className="font-bold">This week</h3><Pill><CalendarDays size={13} />Week 4</Pill></div><div className="mt-5 grid grid-cols-3 gap-2 text-center"><Metric value="7" label="Games" icon={History} /><Metric value="58%" label="Win rate" icon={Medal} /><Metric value="34" label="Puzzles" icon={Puzzle} /></div><div className="mt-5 rounded-2xl bg-emerald-400/8 p-4"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-xl bg-emerald-400/12 text-emerald-300"><Trophy size={17} /></span><div><p className="text-sm font-bold">Tactical eye</p><p className="text-xs text-[var(--text-muted)]">Achievement · 25 puzzle streak</p></div></div></div></Surface>
          <Surface className="p-5"><div className="flex items-center justify-between"><h3 className="font-bold">Ready to play</h3><Users size={18} className="text-[var(--text-faint)]" /></div><div className="mt-3 divide-y divide-[var(--border)]">{housePlayers.slice(0, 3).map((player) => <div key={player.id} className="flex items-center gap-3 py-3"><span className="relative grid size-10 place-items-center rounded-xl text-xl" style={{ backgroundColor: `${player.color}1c`, color: player.color }}>♞<span className="absolute -bottom-0.5 -right-0.5 size-2.5 rounded-full border-2 border-[var(--surface)] bg-emerald-400" /></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{player.name}</p><p className="text-[10px] text-[var(--text-faint)]">{player.rating} · {player.style}</p></div><ButtonLink href={`/play/ai?profile=${player.id}`} variant="ghost" size="sm">Play</ButtonLink></div>)}</div></Surface>
          <Surface className="p-5"><div className="flex items-center justify-between"><h3 className="font-bold">Missions</h3><span className="text-xs font-bold text-[var(--accent)]">2/4</span></div><div className="mt-4 space-y-4"><Mission label="Play one rapid game" progress={100} reward="+40" /><Mission label="Solve 10 puzzles" progress={70} reward="+60" /><Mission label="Review one mistake" progress={0} reward="+35" /></div></Surface>
          <Surface className="border-violet-400/15 bg-violet-400/6 p-5"><div className="flex gap-3"><div className="grid size-11 shrink-0 place-items-center rounded-2xl bg-violet-400/12 text-violet-300"><BrainCircuit size={21} /></div><div><p className="text-sm font-bold">Your AI coach noticed a pattern</p><p className="mt-1 text-xs leading-5 text-[var(--text-muted)]">You&apos;re finding tactics, but moving too quickly after your opponent&apos;s checks.</p><LinkWithArrow href="/analysis">See the pattern</LinkWithArrow></div></div></Surface>
        </div>
      </div>
    </AppShell>
  );
}

function LinkWithArrow({ href, children }: { href: string; children: React.ReactNode }) { return <a href={href} className="mt-2 inline-flex items-center gap-1 text-xs font-bold text-[var(--accent)]">{children}<ArrowRight size={13} /></a>; }
function Metric({ value, label, icon: Icon }: { value: string; label: string; icon: typeof History }) { return <div className="rounded-xl bg-[var(--surface-soft)] px-2 py-3"><Icon size={14} className="mx-auto text-[var(--accent)]" /><p className="mt-2 text-lg font-bold">{value}</p><p className="text-[9px] text-[var(--text-faint)]">{label}</p></div>; }
function Mission({ label, progress, reward }: { label: string; progress: number; reward: string }) { return <div><div className="flex justify-between gap-3 text-xs"><span className={progress === 100 ? "line-through opacity-55" : "font-semibold"}>{label}</span><span className="font-bold text-emerald-400">{reward} XP</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-[var(--surface-raised)]"><div className="h-full rounded-full bg-emerald-400" style={{ width: `${progress}%` }} /></div></div>; }
