import type { Metadata } from "next";
import { ArrowRight, BrainCircuit, Check, ChevronRight, CircleHelp, Flag, Handshake, MousePointer2, RotateCcw, ShieldAlert, Sparkles, Swords } from "lucide-react";
import { PublicPage, BetaNotice } from "../features/_components/public-page";
import { ButtonLink } from "@/components/ui/button";
import { Pill, Surface } from "@/components/ui/surface";

export const metadata: Metadata = { title: "How to play", description: "Learn chess basics, choose a game mode, understand clocks, and start your first game on Busted Minds Chess." };

const steps = [
  { n: "01", title: "Choose a mode", body: "Play Online, challenge the AI, share a local board, or send a private invite. Local and Vs AI do not need an account." },
  { n: "02", title: "Set the pace", body: "Pick a clock, choose rated or casual where available, and decide your color. Try 10+0 rapid if you are new." },
  { n: "03", title: "Make a legal move", body: "Select a piece, then a highlighted square. Dragging, tapping, keyboard input, promotion, castling, and en passant are supported." },
  { n: "04", title: "Finish well", body: "Win by checkmate or time, agree a draw, or resign when the position is settled. Review the game to find one useful lesson." },
];

const pieces = [
  ["♔", "King", "One square in any direction. Keep it out of check."], ["♕", "Queen", "Any distance along a rank, file, or diagonal."],
  ["♖", "Rook", "Any distance horizontally or vertically."], ["♗", "Bishop", "Any distance diagonally; it stays on one color."],
  ["♘", "Knight", "An L-shape: two squares, then one. It can jump."], ["♙", "Pawn", "Moves forward, captures diagonally, and promotes on the last rank."],
];

export default function HowToPlayPage() {
  return <PublicPage eyebrow="A calm first move" title="Learn chess without the lecture." intro="You only need three ideas to begin: protect your king, develop your pieces, and look at what your opponent changed. The interface handles legal moves while you build the rest." aside={<BetaNotice>New to chess? Start in Local or Vs AI with move hints enabled. Those modes work without an account and do not use competitive ratings.</BetaNotice>}>
    <section aria-labelledby="first-game"><div className="flex items-end justify-between gap-4"><div><Pill><Sparkles size={13} />First game in minutes</Pill><h2 id="first-game" className="mt-4 text-3xl font-bold tracking-[-.04em]">From home screen to handshake</h2></div><ButtonLink href="/play" className="hidden sm:inline-flex">Start a game<ArrowRight size={16} /></ButtonLink></div><div className="mt-7 grid gap-4 md:grid-cols-2">{steps.map((step) => <Surface key={step.n} className="flex gap-5 p-6"><span className="font-mono text-sm font-bold text-[var(--accent)]">{step.n}</span><div><h3 className="font-bold">{step.title}</h3><p className="mt-2 text-sm leading-6 text-[var(--text-muted)]">{step.body}</p></div></Surface>)}</div></section>

    <section className="mt-20 grid gap-8 lg:grid-cols-[1.05fr_.95fr] lg:items-start"><div><p className="eyebrow">The board</p><h2 className="mt-3 text-3xl font-bold tracking-[-.04em]">Six pieces, one purpose</h2><p className="mt-3 text-sm leading-6 text-[var(--text-muted)]">White moves first. Each side tries to checkmate the opposing king: attack it so no legal reply escapes the attack.</p><div className="mt-6 grid gap-3 sm:grid-cols-2">{pieces.map(([piece, name, body]) => <div key={name} className="flex gap-3 rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-4"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-[var(--surface-raised)] text-2xl">{piece}</span><div><p className="text-sm font-bold">{name}</p><p className="mt-1 text-xs leading-5 text-[var(--text-muted)]">{body}</p></div></div>)}</div></div><Surface className="overflow-hidden p-5 sm:p-7"><MiniBoard /><div className="mt-5 flex items-start gap-3 rounded-2xl bg-[var(--surface-soft)] p-4"><MousePointer2 size={18} className="mt-0.5 shrink-0 text-[var(--accent)]" /><p className="text-xs leading-5 text-[var(--text-muted)]"><strong className="text-[var(--text)]">Board orientation:</strong> your pieces normally begin closest to you. The lower-right corner is a light square: “light on right.”</p></div></Surface></section>

    <section className="mt-20"><p className="eyebrow">Game choices</p><h2 className="mt-3 text-3xl font-bold tracking-[-.04em]">Pick the room that fits</h2><div className="mt-7 overflow-hidden rounded-[1.4rem] border border-[var(--border)]"><div className="grid grid-cols-[.7fr_1fr_1fr] bg-[var(--surface-soft)] px-4 py-3 text-xs font-bold text-[var(--text-faint)] sm:grid-cols-[.7fr_1fr_1.3fr_1.4fr]"><span>Mode</span><span>Account</span><span className="hidden sm:block">Cloud use</span><span>Best for</span></div>{[["Online","Permanent for rated","Game state","Matchmaking and invites"],["Vs AI","Not required","None by default","Practice at your level"],["Local","Not required","None","Two people, one device"]].map((row) => <div key={row[0]} className="grid grid-cols-[.7fr_1fr_1fr] border-t border-[var(--border)] px-4 py-4 text-sm sm:grid-cols-[.7fr_1fr_1.3fr_1.4fr]"><strong>{row[0]}</strong><span className="text-[var(--text-muted)]">{row[1]}</span><span className="hidden text-[var(--text-muted)] sm:block">{row[2]}</span><span className="text-[var(--text-muted)]">{row[3]}</span></div>)}</div></section>

    <section className="mt-20 grid gap-5 md:grid-cols-3"><RuleCard icon={ShieldAlert} title="Check is a warning" body="If your king is attacked, your next move must remove the attack. You cannot move into check." /><RuleCard icon={Handshake} title="Draws happen" body="Stalemate, repetition, insufficient material, the fifty-move rule, or an accepted offer can end level." /><RuleCard icon={Flag} title="Clocks are decisive" body="Online time is authoritative on the server. Your display counts locally between moves for a smooth clock." /></section>

    <section className="mt-20 rounded-[2rem] border border-[var(--border)] bg-[var(--surface)] p-7 sm:p-9"><div className="grid gap-7 lg:grid-cols-[1fr_auto] lg:items-center"><div><div className="flex items-center gap-2 text-[var(--accent)]"><BrainCircuit size={18} /><span className="text-xs font-bold uppercase tracking-[.16em]">A good next habit</span></div><h2 className="mt-4 text-2xl font-bold">Before every move, ask three questions.</h2><div className="mt-5 space-y-3">{["What did my opponent’s last move attack?", "Are either king, queen, or an undefended piece in danger?", "Do I have a check, capture, or threat that is actually safe?"].map((item) => <p key={item} className="flex gap-3 text-sm text-[var(--text-muted)]"><Check size={17} className="shrink-0 text-emerald-300" />{item}</p>)}</div></div><div className="flex flex-wrap gap-3 lg:flex-col"><ButtonLink href="/play/ai"><Swords size={16} />Practice vs AI</ButtonLink><ButtonLink href="/faq" variant="secondary"><CircleHelp size={16} />Read the FAQ</ButtonLink><ButtonLink href="/analysis" variant="ghost"><RotateCcw size={16} />Open analysis<ChevronRight size={14} /></ButtonLink></div></div></section>
  </PublicPage>;
}

function RuleCard({ icon: Icon, title, body }: { icon: typeof Flag; title: string; body: string }) { return <Surface className="p-6"><Icon size={21} className="text-[var(--accent)]" /><h3 className="mt-5 font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-[var(--text-muted)]">{body}</p></Surface>; }

function MiniBoard() { const setup = ["♜♞♝♛♚♝♞♜", "♟♟♟♟♟♟♟♟", "", "", "", "", "♙♙♙♙♙♙♙♙", "♖♘♗♕♔♗♘♖"]; return <div className="mx-auto aspect-square w-full max-w-[390px] overflow-hidden rounded-xl border-4 border-[#13283b] shadow-2xl">{setup.flatMap((rank, r) => Array.from({ length: 8 }, (_, f) => <div key={`${r}-${f}`} className={`relative float-left grid h-[12.5%] w-[12.5%] place-items-center text-[clamp(1.25rem,5vw,2.5rem)] ${(r + f) % 2 ? "bg-[#49768c]" : "bg-[#c4d9df]"}`}><span className={r < 2 ? "text-[#071522] drop-shadow-sm" : "text-white drop-shadow-[0_1px_1px_rgba(0,0,0,.8)]"}>{rank[f] ?? ""}</span></div>))}</div>; }
