import type { Metadata } from "next";
import { ArrowUpRight, Box, Code2, FileCode2, Scale, ShieldCheck } from "lucide-react";
import { PublicPage, BetaNotice } from "../features/_components/public-page";
import { Pill, Surface } from "@/components/ui/surface";

export const metadata: Metadata = { title: "Open-source licenses", description: "Third-party software notices and source links for Stockfish, react-chessboard, chess.js, Lucide, and Supabase libraries used by Busted Minds Chess." };

const projects = [
  { name: "Stockfish.js / Stockfish 18", version: "18.0.8", license: "GNU GPL v3.0", description: "Chess engine used for browser-based analysis and computer play. The distributed WebAssembly and JavaScript build is covered by GPLv3.", source: "https://github.com/nmrugg/stockfish.js", licenseHref: "/stockfish/COPYING.txt" },
  { name: "react-chessboard", version: "5.10.0", license: "MIT", description: "Responsive React chessboard interface by Ryan Gregory and contributors.", source: "https://github.com/Clariity/react-chessboard" },
  { name: "chess.js", version: "1.4.0", license: "BSD-2-Clause", description: "Move generation, validation, check, checkmate, draw, FEN, and PGN utilities.", source: "https://github.com/jhlywa/chess.js" },
  { name: "Lucide", license: "ISC", description: "Interface icon library used throughout the application.", source: "https://github.com/lucide-icons/lucide" },
  { name: "Supabase JavaScript & SSR", version: "2.110.7 / 0.12.3", license: "MIT", description: "Database, authentication, Realtime, storage, and server-rendering client libraries.", source: "https://github.com/supabase/supabase-js" },
];

export default function LicensesPage() { return <PublicPage eyebrow="Built on generous work" title="Open-source licenses" intro="Modern chess software stands on decades of shared engineering. These notices identify the major open-source components distributed with or used by Busted Minds Chess." aside={<BetaNotice>Exact resolved dependency versions are recorded in the project lockfile. Transitive packages retain their own copyrights and licenses.</BetaNotice>}>
  <section className="grid gap-4 lg:grid-cols-2">{projects.map((project) => <Surface key={project.name} className="flex flex-col p-6"><div className="flex items-start justify-between gap-4"><span className="grid size-11 place-items-center rounded-2xl bg-[var(--accent-soft)] text-[var(--accent)]"><Box size={20} /></span><Pill>{project.license}</Pill></div><h2 className="mt-5 text-lg font-bold">{project.name}</h2>{project.version && <p className="mt-1 text-xs text-[var(--text-faint)]">Version {project.version}</p>}<p className="mt-3 flex-1 text-sm leading-6 text-[var(--text-muted)]">{project.description}</p><div className="mt-5 flex flex-wrap gap-4"><ExternalLink href={project.source}><Code2 size={14} />Source</ExternalLink>{project.licenseHref && <a href={project.licenseHref} className="inline-flex items-center gap-1.5 text-xs font-bold text-[var(--accent)] hover:underline"><FileCode2 size={14} />License text</a>}</div></Surface>)}</section>
  <section className="mt-10 grid gap-5 md:grid-cols-2"><Surface className="border-violet-400/15 bg-violet-400/[.05] p-6"><Scale size={21} className="text-violet-300" /><h2 className="mt-4 font-bold">Stockfish source obligations</h2><p className="mt-2 text-sm leading-6 text-[var(--text-muted)]">The included Stockfish build is free software under GPLv3. Corresponding source is available from the linked upstream repository and npm source package. Distributors of modified binaries must satisfy the GPLv3 source requirements.</p></Surface><Surface className="border-emerald-400/15 bg-emerald-400/[.05] p-6"><ShieldCheck size={21} className="text-emerald-300" /><h2 className="mt-4 font-bold">Brand assets</h2><p className="mt-2 text-sm leading-6 text-[var(--text-muted)]">Busted Minds Chess logos, Busted Minds company logos, original visual design, and original editorial content are not granted under the software licenses listed here unless a separate notice says otherwise.</p></Surface></section>
  <p className="mt-8 text-xs leading-5 text-[var(--text-faint)]">This page is a readable summary, not a replacement for the complete license texts. The repository’s THIRD_PARTY_NOTICES file and each package’s license are authoritative.</p>
  </PublicPage>; }

function ExternalLink({ href, children }: { href: string; children: React.ReactNode }) { return <a href={href} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1.5 text-xs font-bold text-[var(--accent)] hover:underline">{children}<ArrowUpRight size={12} /></a>; }
